-- Gesture dictionary (generated from src/data). Safe to run again.
insert into public.gestures (id, label, category, kind) values
  ('letter-1', 'А', 'letter', 'static'),
  ('letter-2', 'Б', 'letter', 'static'),
  ('letter-3', 'В', 'letter', 'static'),
  ('letter-4', 'Г', 'letter', 'static'),
  ('letter-5', 'Е', 'letter', 'static'),
  ('letter-6', 'И', 'letter', 'static'),
  ('letter-7', 'Л', 'letter', 'static'),
  ('letter-8', 'М', 'letter', 'static'),
  ('letter-9', 'Н', 'letter', 'static'),
  ('letter-10', 'О', 'letter', 'static'),
  ('letter-11', 'П', 'letter', 'static'),
  ('letter-12', 'С', 'letter', 'static'),
  ('letter-13', 'Т', 'letter', 'static'),
  ('letter-14', 'У', 'letter', 'static'),
  ('letter-15', 'Ш', 'letter', 'static'),
  ('letter-16', 'Д', 'letter', 'dynamic'),
  ('letter-17', 'Ё', 'letter', 'dynamic'),
  ('letter-18', 'Ж', 'letter', 'static'),
  ('letter-19', 'З', 'letter', 'dynamic'),
  ('letter-20', 'Й', 'letter', 'dynamic'),
  ('letter-21', 'К', 'letter', 'static'),
  ('letter-22', 'Р', 'letter', 'static'),
  ('letter-23', 'Ф', 'letter', 'static'),
  ('letter-24', 'Х', 'letter', 'static'),
  ('letter-25', 'Ц', 'letter', 'dynamic'),
  ('letter-26', 'Ч', 'letter', 'static'),
  ('letter-27', 'Щ', 'letter', 'dynamic'),
  ('letter-28', 'Ъ', 'letter', 'dynamic'),
  ('letter-29', 'Ы', 'letter', 'static'),
  ('letter-30', 'Ь', 'letter', 'static'),
  ('letter-31', 'Э', 'letter', 'static'),
  ('letter-32', 'Ю', 'letter', 'static'),
  ('letter-33', 'Я', 'letter', 'static'),
  ('word-hello', 'Привет', 'word', 'dynamic'),
  ('word-goodbye', 'До свидания', 'word', 'dynamic'),
  ('word-yes', 'Да', 'word', 'dynamic'),
  ('word-no', 'Нет', 'word', 'dynamic'),
  ('word-thanks', 'Спасибо', 'word', 'dynamic'),
  ('word-please', 'Пожалуйста', 'word', 'dynamic'),
  ('word-sorry', 'Извините', 'word', 'dynamic'),
  ('word-name', 'Имя', 'word', 'dynamic'),
  ('word-me', 'Я', 'word', 'dynamic'),
  ('word-you', 'Вы', 'word', 'dynamic'),
  ('word-help', 'Помощь', 'word', 'dynamic'),
  ('word-repeat', 'Повторите', 'word', 'dynamic'),
  ('word-understand', 'Понимать', 'word', 'dynamic'),
  ('word-home', 'Дом', 'word', 'dynamic'),
  ('word-water', 'Вода', 'word', 'dynamic')
on conflict (id) do update set label = excluded.label, category = excluded.category, kind = excluded.kind;

-- After registering, make yourself an admin (replace the email):
-- update public.profiles set role = 'admin'
-- where id = (select id from auth.users where email = 'you@example.com');
